NAME = BraiiiiiiinnnzzzZ
BraiiiiiiinnnzzzZ= BraiiiiiiinnnzzzZ

SRC = 	main.cpp \
	Zombie.cpp \
	randomChump.cpp \
	newZombie.cpp

CXX = c++ 

CXXFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(BraiiiiiiinnnzzzZ)

$(NAME): all 

$(BraiiiiiiinnnzzzZ):
	$(CXX) $(CXXFLAGS) $(SRC) -o $(BraiiiiiiinnnzzzZ)
        
clean:
	rm -rf $(BraiiiiiiinnnzzzZ)

re: fclean all 

fclean: clean

.PHONY: all fclean clean re
